apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-langgraph-agent-deployment
  labels:
    app: my-langgraph-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-langgraph-agent
  template:
    metadata:
      labels:
        app: my-langgraph-agent
    spec:
      containers:
      - name: my-langgraph-agent
        image: quay.io/burrsutter/my-langgraph-agent:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MCP_SERVER_URL
          value: "http://mcp-server-service:9005/mcp"
        - name: API_PORT
          value: "8000"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
