apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
