apiVersion: v1
kind: Service
metadata:
  name: mcp-server-service
  labels:
    app: mcp-server
spec:
  type: ClusterIP
  selector:
    app: mcp-server
  ports:
  - port: 9005
    targetPort: 9005
    protocol: TCP
    name: http
